app/WhyJoinUs/Reasons.tsx, app/WhyJoinUs/page.tsx, app/page.tsx
-update font color and background in why join us section
-add to landing page
=> Enhancement in CODE-4

app/Footer/page.tsx
-removing focus outline in input
=> Enhancement in CODE-6

Components/Avatars.tsx, app/CoDevs/Section/Section2.tsx, styles/calendar.scss
=> Fixed_Calendar

app/CoDevs/page.tsx, app/Interns/DummyData.tsx, tailwind.config.js
-add custom colors in tailwind config
-refactor codevs section (ui only)
-update dummy data
=> Refactor Codevs Section

app/CoDevs/page.tsx
-update colors
-fix icon issue
-adjust width
=> Adjust width, fix icons and colors

app/CoDevs/page.tsx, app/Interns/page.tsx, app/projects-completed/[projectId]/page.tsx, app/projects-completed/page.tsx
-fixed background color problem in "Projects Completed Page"
-fixed sidebar and icon issue in "Interns Page"
-adjust width in filter container in "Codevs Section"
=> fixed Codevs Section, Interns Page, and Projects Page

Components/ui/pagination/button.tsx, Components/ui/pagination/pagination.tsx, app/(protectedroutes)/todo/TodoCard.tsx, app/(protectedroutes)/todo/page.tsx, assets/icons.tsx, yarn.lock
=> Created Todo Page

app/(protectedroutes)/dashboard/components/TimeTracker.tsx
=> Updated Time tracker component

app/(protectedroutes)/dashboard/components/Calendar.tsx
=> new: calendar

app/(protectedroutes)/Interns/components/FilterInterns.tsx, app/(protectedroutes)/Interns/components/InternCard.tsx, app/(protectedroutes)/Interns/components/InternList.tsx
=> interns api integration

Components/ui/tabs/tabs.tsx, app/(protectedroutes)/profile/components/About.tsx, app/(protectedroutes)/profile/components/ActivityLog.tsx, app/(protectedroutes)/profile/components/Notifications.tsx, app/(protectedroutes)/profile/components/ProfileInfo.tsx, app/(protectedroutes)/profile/components/Settings.tsx, app/(protectedroutes)/profile/page.tsx, package.json, yarn.lock
=> created side tabs for profile page

app/(landingPage)/Footer.tsx, app/auth/signin/page.tsx, app/auth/signup/page.tsx
=> fixed logos and background

app/(landingPage)/codevs/CodevsCard.tsx
=> fix codevs card mobile column

app/(landingPage)/Navbar.tsx, app/(landingPage)/codevs/page.tsx
=> fix home mobile menu

app/(landingPage)/codevs/CodevsCard.tsx, app/(protectedroutes)/interns/InternCard.tsx, app/(protectedroutes)/interns/InternList.tsx, app/(protectedroutes)/interns/page.tsx
=> 129 fe codevs add bg for tablet mobile

app/(protectedroutes)/interns/InternCard.tsx, app/(protectedroutes)/interns/InternList.tsx, app/(protectedroutes)/interns/page.tsx
=> fix columns in interns

app/(protectedroutes)/applicants/loading.tsx
fix: update skeleton loading page for applicants
=> 125 fe skeleton applicants

app/(landingPage)/codevs/CodevsCard.tsx, app/(protectedroutes)/interns/InternCard.tsx, app/(protectedroutes)/interns/InternList.tsx
=> Remove Color Styles in Interns

app/(protectedroutes)/dashboard/components/Todo.tsx, app/(protectedroutes)/dashboard/components/TodoList.tsx
=> todo list api integration

app/(protectedroutes)/todo/TodoCard.tsx, app/(protectedroutes)/todo/page.tsx
=> Todo api integration

app/(protectedroutes)/time-tracker/TimeTrackerTable.tsx
- I created a plain table structure
- Added dummy details
- Added array of 10 as sample
=> Created Time Tracker Table Structure

app/auth/signin/SigninInputs.tsx
removed class="(invert)" on eyeIcon svg
=> fix eye icon on sign in

app/auth/signin/page.tsx, app/auth/signup/page.tsx
removed class="(h-screen)" to occupy styles full height
=> fix sign in, sign up layout

Components/shared/dashboard/Navbar.tsx
Added bell icon on dashboard navbar
=> fix bell icon on dashboard navbar

app/auth/signin/page.tsx, app/auth/signup/page.tsx
applied min-h-screen class to signin & signup container to avoid white spaces below
=> chore/signin & signup layout

app/(protectedroutes)/todo/TodoCard.tsx, app/(protectedroutes)/todo/loading.tsx, app/(protectedroutes)/todo/page.tsx
- created loading page next js feature to implement skeleton on loading state
- transferred add new todo component to Todo page to avoid duplicates on map
=> Skeleton Todos

Components/modals/techstack-modal.tsx
=> fix sign up tech stack selected color

Components/shared/dashboard/Theme.tsx
Refactor code logic
Inverted icon color for dark mode
Fix the position of icons
Made the icons function as one
// previous codes were formatted as comments, will clean the file once reviewed
=> Modified switch

Components/modals/TodoAddModal.tsx
- applied useEffect to fetch Projects Data on the client
- replaced dummy projects data with real time projects data to display on select items
=> get projects and display to select items

app/(landingPage)/Navbar.tsx
=> fix mobile menu background

constants/index.ts
=> add Kanban sidebar menu

app/(protectedroutes)/clients/page.tsx, app/(protectedroutes)/projects/page.tsx
=> display action buttons on projects

Components/modals/TodoAddModal.tsx
- declaration of state for tags storage
- create handleAddTag function to populate tags
- dynamic display tags
=> implement todo adding tag function
